name: Build & Push Docker Images

on:
  push:
    branches:
      - master
  release:
    types: [published]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-amd64:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version from release tag
        if: github.event_name == 'release'
        id: version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build and push AMD64 Docker image
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: |
          DOCKERFILE=app.dockerfile
          IMAGE_REPO=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          docker buildx build --platform linux/amd64 \
            --cache-from=type=registry,ref=${IMAGE_REPO}:amd64 \
            --cache-to=type=inline \
            --provenance false \
            -f $DOCKERFILE \
            -t ${IMAGE_REPO}:amd64 \
            --push .

      - name: Build and push AMD64 release Docker image
        if: github.event_name == 'release'
        run: |
          DOCKERFILE=app.dockerfile
          IMAGE_REPO=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          docker buildx build --platform linux/amd64 \
            --cache-from=type=registry,ref=${IMAGE_REPO}:${{ env.RELEASE_VERSION }}-amd64 \
            --cache-to=type=inline \
            --provenance false \
            -f $DOCKERFILE \
            -t ${IMAGE_REPO}:${{ env.RELEASE_VERSION }}-amd64 \
            --push .

  build-arm64:
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version from release tag
        if: github.event_name == 'release'
        id: version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build and push ARM64 Docker image
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: |
          DOCKERFILE=app.dockerfile
          IMAGE_REPO=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          docker buildx build --platform linux/arm64 \
            --cache-from=type=registry,ref=${IMAGE_REPO}:arm64 \
            --cache-to=type=inline \
            --provenance false \
            -f $DOCKERFILE \
            -t ${IMAGE_REPO}:arm64 \
            --push .

      - name: Build and push ARM64 release Docker image
        if: github.event_name == 'release'
        run: |
          DOCKERFILE=app.dockerfile
          IMAGE_REPO=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          docker buildx build --platform linux/arm64 \
            --cache-from=type=registry,ref=${IMAGE_REPO}:${{ env.RELEASE_VERSION }}-arm64 \
            --cache-to=type=inline \
            --provenance false \
            -f $DOCKERFILE \
            -t ${IMAGE_REPO}:${{ env.RELEASE_VERSION }}-arm64 \
            --push .

  manifest:
    needs: [build-amd64, build-arm64]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version from release tag
        if: github.event_name == 'release'
        id: version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Create and push multi-arch manifest for main
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: |
          IMAGE_REPO=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          docker manifest create ${IMAGE_REPO}:main \
            --amend ${IMAGE_REPO}:amd64 \
            --amend ${IMAGE_REPO}:arm64
          docker manifest push ${IMAGE_REPO}:main

      - name: Create and push multi-arch manifest for releases
        if: github.event_name == 'release'
        run: |
          IMAGE_REPO=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          docker manifest create ${IMAGE_REPO}:${{ env.RELEASE_VERSION }} \
            --amend ${IMAGE_REPO}:${{ env.RELEASE_VERSION }}-amd64 \
            --amend ${IMAGE_REPO}:${{ env.RELEASE_VERSION }}-arm64
          docker manifest push ${IMAGE_REPO}:${{ env.RELEASE_VERSION }}
